### ISSUE TITLE
Advanced Guide for LXD

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#413]
We added an advanced guide on the linuxcontainers.org website:
https://linuxcontainers.org/lxd/advanced-guide/

Below you find a Todo-list.
You can help by:
- creating a pull request to add content or 
- adding a comment with ideas for changes or further content.

You find the source-file of the advanced guide here:
https://github.com/lxc/linuxcontainers.org/blob/master/content/lxd/advanced-guide.md

**Todo-List:**
Improvements:
- [ ] add links to manpages (once #471 is implemented)

Content:
- [ ] Instance management - Part 2
    - might describe details like snapshots etc.
- [ ] Server configuration (partly added)
    - recent security recommendations
    - custom user mappings: https://ubuntu.com/blog/custom-user-mappings-in-lxd-containers
- [ ] Clustering, a link to the documentation could be enough: https://linuxcontainers.org/lxd/docs/master/clustering
- [ ] Networks 
- [ ] Storages
- [ ] Devices
- [ ] GUI in containers (see e.g.: [LXD Forum - Overview GUI in containers](https://discuss.linuxcontainers.org/t/overview-gui-inside-containers/8767)
- [ ] GUI in virtual machines (see e.g.: [LXD Forum - GUI in VM's](https://discuss.linuxcontainers.org/t/howto-gui-in-virtual-machines-vms/9223))
- [ ] LXD-p2c (Create containers from existing systems (e.g. servers, virtual machines etc.)); see also: [forum - howto use lxd p2c](https://discuss.linuxcontainers.org/t/howto-use-lxd-p2c/3574) and [forum - question about lxd p2c](https://discuss.linuxcontainers.org/t/advanced-guide-questions-about-lxd-p2c/9205) (was also requested in #340)
- [ ] More Content for Tips & Tricks  (first added in #437)
- [ ] Backup and Emergency guide (we could maybe just link to https://github.com/lxc/lxd/blob/master/doc/backup.md)
- [ ] Guide for setting Limits (for example kernel and CPU limits)

Done:
- [x] Configuration of instances (lxc launch, profiles) (added in #434)
  Note: includes only a description on how to apply options, so no description of the options themself
- [x] Cloud-init (added in #435)
- [x] Remote Servers (see also #431) (added in #435)
- [x] Images - part 2 (build images) (added in #437)
- [x] Command Aliases (added in #437)
- [x] Further Links (added in #434)

---

**Sorted out:**
Technical:
- [blocked] other style for tables (reduced width, vertical borders) (see: #420) [H]

---

**Original Post:**
We (the LXD-community, including the developers) could create an additional "Advanced Guide" that we link to in "Getting started", that could include topics like:
* networks
* storage pools
* devices
* cloud-init
* Clustering
etc.

Advantages:
* This could be a good introduction to advanced topics for new users.
* It could also help to seperate in-depth-topics from the Getting Started-doc.
* The regular [documentation](https://github.com/lxc/lxd/tree/master/doc) could be kept technical and rather short-summarized, while an advanced guide could formulate things in more detail.

**Comment by toby63** [comment]
@simos would you contribute on this?
